//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.AidSysWebServiceSoap")]
    public interface AidSysWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name tellno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginTest", ReplyAction="*")]
        TestService.ServiceReference1.LoginTestResponse LoginTest(TestService.ServiceReference1.LoginTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginTest", Namespace="http://tempuri.org/", Order=0)]
        public TestService.ServiceReference1.LoginTestRequestBody Body;
        
        public LoginTestRequest() {
        }
        
        public LoginTestRequest(TestService.ServiceReference1.LoginTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tellno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orgno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pwd;
        
        public LoginTestRequestBody() {
        }
        
        public LoginTestRequestBody(string tellno, string orgno, string pwd) {
            this.tellno = tellno;
            this.orgno = orgno;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestService.ServiceReference1.LoginTestResponseBody Body;
        
        public LoginTestResponse() {
        }
        
        public LoginTestResponse(TestService.ServiceReference1.LoginTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginTestResult;
        
        public LoginTestResponseBody() {
        }
        
        public LoginTestResponseBody(bool LoginTestResult) {
            this.LoginTestResult = LoginTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AidSysWebServiceSoapChannel : TestService.ServiceReference1.AidSysWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AidSysWebServiceSoapClient : System.ServiceModel.ClientBase<TestService.ServiceReference1.AidSysWebServiceSoap>, TestService.ServiceReference1.AidSysWebServiceSoap {
        
        public AidSysWebServiceSoapClient() {
        }
        
        public AidSysWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AidSysWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AidSysWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AidSysWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestService.ServiceReference1.LoginTestResponse TestService.ServiceReference1.AidSysWebServiceSoap.LoginTest(TestService.ServiceReference1.LoginTestRequest request) {
            return base.Channel.LoginTest(request);
        }
        
        public bool LoginTest(string tellno, string orgno, string pwd) {
            TestService.ServiceReference1.LoginTestRequest inValue = new TestService.ServiceReference1.LoginTestRequest();
            inValue.Body = new TestService.ServiceReference1.LoginTestRequestBody();
            inValue.Body.tellno = tellno;
            inValue.Body.orgno = orgno;
            inValue.Body.pwd = pwd;
            TestService.ServiceReference1.LoginTestResponse retVal = ((TestService.ServiceReference1.AidSysWebServiceSoap)(this)).LoginTest(inValue);
            return retVal.Body.LoginTestResult;
        }
    }
}
