//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace TestService.AidWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestWebServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback TellerAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObjParamaterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TestService.Properties.Settings.Default.TestService_AidWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestWebServiceCompletedEventHandler TestWebServiceCompleted;
        
        /// <remarks/>
        public event TellerAuthCompletedEventHandler TellerAuthCompleted;
        
        /// <remarks/>
        public event ObjParamaterCompletedEventHandler ObjParamaterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestWebService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult TestWebService() {
            object[] results = this.Invoke("TestWebService", new object[0]);
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void TestWebServiceAsync() {
            this.TestWebServiceAsync(null);
        }
        
        /// <remarks/>
        public void TestWebServiceAsync(object userState) {
            if ((this.TestWebServiceOperationCompleted == null)) {
                this.TestWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestWebServiceOperationCompleted);
            }
            this.InvokeAsync("TestWebService", new object[0], this.TestWebServiceOperationCompleted, userState);
        }
        
        private void OnTestWebServiceOperationCompleted(object arg) {
            if ((this.TestWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestWebServiceCompleted(this, new TestWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TellerAuth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult TellerAuth(string tellno, string orgno, string pwd) {
            object[] results = this.Invoke("TellerAuth", new object[] {
                        tellno,
                        orgno,
                        pwd});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void TellerAuthAsync(string tellno, string orgno, string pwd) {
            this.TellerAuthAsync(tellno, orgno, pwd, null);
        }
        
        /// <remarks/>
        public void TellerAuthAsync(string tellno, string orgno, string pwd, object userState) {
            if ((this.TellerAuthOperationCompleted == null)) {
                this.TellerAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTellerAuthOperationCompleted);
            }
            this.InvokeAsync("TellerAuth", new object[] {
                        tellno,
                        orgno,
                        pwd}, this.TellerAuthOperationCompleted, userState);
        }
        
        private void OnTellerAuthOperationCompleted(object arg) {
            if ((this.TellerAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TellerAuthCompleted(this, new TellerAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObjParamater", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializationObj ObjParamater(SerializationObj obj) {
            object[] results = this.Invoke("ObjParamater", new object[] {
                        obj});
            return ((SerializationObj)(results[0]));
        }
        
        /// <remarks/>
        public void ObjParamaterAsync(SerializationObj obj) {
            this.ObjParamaterAsync(obj, null);
        }
        
        /// <remarks/>
        public void ObjParamaterAsync(SerializationObj obj, object userState) {
            if ((this.ObjParamaterOperationCompleted == null)) {
                this.ObjParamaterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObjParamaterOperationCompleted);
            }
            this.InvokeAsync("ObjParamater", new object[] {
                        obj}, this.ObjParamaterOperationCompleted, userState);
        }
        
        private void OnObjParamaterOperationCompleted(object arg) {
            if ((this.ObjParamaterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObjParamaterCompleted(this, new ObjParamaterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResult {
        
        private int resultCodeField;
        
        private string outMsgField;
        
        private string sysErrField;
        
        private byte[] resultField;
        
        private string exceptionMsgField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OutMsg {
            get {
                return this.outMsgField;
            }
            set {
                this.outMsgField = value;
            }
        }
        
        /// <remarks/>
        public string SysErr {
            get {
                return this.sysErrField;
            }
            set {
                this.sysErrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionMsg {
            get {
                return this.exceptionMsgField;
            }
            set {
                this.exceptionMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SerializationObj {
        
        private System.DateTime newDateField;
        
        private string[] nameListField;
        
        /// <remarks/>
        public System.DateTime NewDate {
            get {
                return this.newDateField;
            }
            set {
                this.newDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("String")]
        public string[] NameList {
            get {
                return this.nameListField;
            }
            set {
                this.nameListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TestWebServiceCompletedEventHandler(object sender, TestWebServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TellerAuthCompletedEventHandler(object sender, TellerAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TellerAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TellerAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObjParamaterCompletedEventHandler(object sender, ObjParamaterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObjParamaterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObjParamaterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializationObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializationObj)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591